# Generated by Django 6.0.3 on 2026-03-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_number',
            field=models.CharField(default='temp', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='instrument_serial',
            field=models.CharField(default='UNKNOWN', max_length=100),
            preserve_default=False,
        ),
    ]
