# Generated by Django 6.0.3 on 2026-03-07 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_certificate_certificate_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='instrument_serial',
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_serial', models.CharField(max_length=100)),
                ('instrument_name', models.CharField(max_length=200)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.certificate')),
            ],
        ),
    ]
