# Generated by Django 6.0.3 on 2026-03-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_remove_certificate_instrument_serial_instrument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_file',
            field=models.FileField(upload_to='media/certificates/'),
        ),
    ]
